name: github-actions
on:
  push:
  workflow_dispatch:
    branches:
      - openapi
    inputs:
      branch_name:
        description: 'OAS branch name'
        required: true
        type: string

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: set branch name variable
        run: |
          if [ -z ${{ inputs.branch_name }} ]
          then
            echo "branch_name=oas-release" >> $GITHUB_ENV
          else
            echo "branch_name=${{ inputs.branch_name }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: '0'
      - run: |
          git submodule set-branch --branch ${{ env.branch_name }} oas
          git submodule update --init --recursive --remote
          cd oas && git fetch origin && git checkout ${{ env.branch_name }}
          cd ../
          ./run-build
